autolog:
  loggers:
    - JdbcAdapter

spring:
  datasource:
    initialization-mode: embedded
    platform: h2
    url: jdbc:h2:mem:example
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2